import assert from 'node:assert/strict';
import {createMovement} from '../dist/movement.mjs';
import {step} from '../dist/walk-map.mjs';
let arrivals=0;
const m=createMovement({x:11,y:9},step,()=>arrivals++);
m.press('right',[1,0],0);
assert.equal(m.tick(75).x,11.5,'movement interpolates between tiles');
m.tick(150);m.tick(300);m.tick(450);
assert.equal(m.position.x,14,'held input continues across tiles');
m.release('right');m.tick(600);m.tick(2000);
assert.equal(m.position.x,15,'release finishes current tile and stops');
m.press('down',[0,1],2000);m.tick(2150);m.tick(2300);m.tick(3000);
assert.deepEqual(m.position,{x:15,y:11},'shop walls block held movement');
m.clear();m.reset();assert.equal(arrivals,6);
let entered=0;
const visit=createMovement({x:15,y:10},step,()=>{entered++;visit.clear()});
visit.press('down',[0,1],0);visit.tick(150);visit.tick(500);
assert.equal(entered,1,'arrival can stop held input when opening a shop');
assert.equal(visit.moving,false);
console.log('PASS: interpolation, continuous hold, release, collisions, reset, and shop entry stop.');
