// Dependency-free build for the existing static game. Run: node .openai/build.mjs
import {readFile,writeFile,cp,access,rm} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const names=['characters','relationships','clues','locations','phases','suspectReview','minekoApartmentEvidence'];
const data={};
for(const name of names)data[name]=JSON.parse(await readFile(new URL(`data/${name}.json`,root),'utf8'));
for(const npc of Object.values(data.characters))for(const path of Object.values(npc.portraits))await access(new URL('public/'+path,root));
for(const clue of data.clues.entries)if(!data.locations.map.locations.some(l=>l.id===clue.locationId))throw Error('Unknown clue location: '+clue.locationId);
await access(new URL('src/index.html',root));
await rm(new URL('dist/',root),{recursive:true,force:true});
await cp(new URL('src/',root),new URL('dist/',root),{recursive:true});
await cp(new URL('public/',root),new URL('dist/',root),{recursive:true});
await writeFile(new URL('dist/game-data.mjs',root),'// Generated by .openai/build.mjs; edit root data/*.json instead.\n'+names.map(name=>`export const ${name}=${JSON.stringify(data[name],null,2)};`).join('\n')+'\n');
console.log(`Built dist from src, public, and ${names.length} data files.`);
